name: weather
description: View weather.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter

  geolocator: ^9.0.2
  geolocator_apple: ^2.1.2
  geolocator_linux: ^0.1.0
  handy_window: ^0.3.1
  intl: ^0.18.0
  open_weather_client: ^2.1.0
  provider: ^6.0.5
  safe_change_notifier: ^0.2.0
  yaru: ^0.5.3
  yaru_colors: ^0.1.4
  yaru_icons: ^1.0.3
  yaru_widgets: ^2.0.0-beta-4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/apikey.json
