name: weather
title: Weather
base: core22
version: '0.1'
summary: A beautiful weather app made with Flutter, and Yaru widgets.
description: |
  A beautiful weather app made with Flutter, and Yaru widgets.
source-code: https://github.com/ubuntu-flutter-community/weather
issues: https://github.com/ubuntu-flutter-community/weather/issues
license: MPL-2.0


compression: lzo
grade: stable
confinement: devmode # use 'strict' once you have the right plugs and slots
architectures: [amd64]

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-branch: stable
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
      - xz-utils
      - zip
    prime:
      - -*

  weather:
    plugin: nil
    source: https://github.com/peter-kal/weather.git
    after: [flutter-git]
    
    override-build: |
      set -eux
      flutter doctor
      flutter pub get
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/ 

slots:
  weather-dbus: 
   interface: dbus
   bus: session
   name: org.ubuntu_flutter_community.Weather

apps:
  weather:
   command: bin/weather
   desktop: snap/gui/weather.desktop
   extensions: [gnome]
   plugs:
    - network
    - x11
    - wayland 
    - desktop 
    - desktop-legacy
    - unity7 